
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UploadHistory` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model UploadHistory
 * 
 */
export type UploadHistoryModel = runtime.Types.Result.DefaultSelection<Prisma.$UploadHistoryPayload>

export type AggregateUploadHistory = {
  _count: UploadHistoryCountAggregateOutputType | null
  _avg: UploadHistoryAvgAggregateOutputType | null
  _sum: UploadHistorySumAggregateOutputType | null
  _min: UploadHistoryMinAggregateOutputType | null
  _max: UploadHistoryMaxAggregateOutputType | null
}

export type UploadHistoryAvgAggregateOutputType = {
  fileSize: number | null
  rowCount: number | null
  errorCount: number | null
}

export type UploadHistorySumAggregateOutputType = {
  fileSize: number | null
  rowCount: number | null
  errorCount: number | null
}

export type UploadHistoryMinAggregateOutputType = {
  id: string | null
  userId: string | null
  filename: string | null
  fileSize: number | null
  rowCount: number | null
  errorCount: number | null
  status: string | null
  createdAt: Date | null
}

export type UploadHistoryMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  filename: string | null
  fileSize: number | null
  rowCount: number | null
  errorCount: number | null
  status: string | null
  createdAt: Date | null
}

export type UploadHistoryCountAggregateOutputType = {
  id: number
  userId: number
  filename: number
  fileSize: number
  rowCount: number
  errorCount: number
  errors: number
  status: number
  createdAt: number
  _all: number
}


export type UploadHistoryAvgAggregateInputType = {
  fileSize?: true
  rowCount?: true
  errorCount?: true
}

export type UploadHistorySumAggregateInputType = {
  fileSize?: true
  rowCount?: true
  errorCount?: true
}

export type UploadHistoryMinAggregateInputType = {
  id?: true
  userId?: true
  filename?: true
  fileSize?: true
  rowCount?: true
  errorCount?: true
  status?: true
  createdAt?: true
}

export type UploadHistoryMaxAggregateInputType = {
  id?: true
  userId?: true
  filename?: true
  fileSize?: true
  rowCount?: true
  errorCount?: true
  status?: true
  createdAt?: true
}

export type UploadHistoryCountAggregateInputType = {
  id?: true
  userId?: true
  filename?: true
  fileSize?: true
  rowCount?: true
  errorCount?: true
  errors?: true
  status?: true
  createdAt?: true
  _all?: true
}

export type UploadHistoryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UploadHistory to aggregate.
   */
  where?: Prisma.UploadHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UploadHistories to fetch.
   */
  orderBy?: Prisma.UploadHistoryOrderByWithRelationInput | Prisma.UploadHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UploadHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UploadHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UploadHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UploadHistories
  **/
  _count?: true | UploadHistoryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UploadHistoryAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UploadHistorySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UploadHistoryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UploadHistoryMaxAggregateInputType
}

export type GetUploadHistoryAggregateType<T extends UploadHistoryAggregateArgs> = {
      [P in keyof T & keyof AggregateUploadHistory]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUploadHistory[P]>
    : Prisma.GetScalarType<T[P], AggregateUploadHistory[P]>
}




export type UploadHistoryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UploadHistoryWhereInput
  orderBy?: Prisma.UploadHistoryOrderByWithAggregationInput | Prisma.UploadHistoryOrderByWithAggregationInput[]
  by: Prisma.UploadHistoryScalarFieldEnum[] | Prisma.UploadHistoryScalarFieldEnum
  having?: Prisma.UploadHistoryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UploadHistoryCountAggregateInputType | true
  _avg?: UploadHistoryAvgAggregateInputType
  _sum?: UploadHistorySumAggregateInputType
  _min?: UploadHistoryMinAggregateInputType
  _max?: UploadHistoryMaxAggregateInputType
}

export type UploadHistoryGroupByOutputType = {
  id: string
  userId: string
  filename: string
  fileSize: number
  rowCount: number
  errorCount: number
  errors: runtime.JsonValue | null
  status: string
  createdAt: Date
  _count: UploadHistoryCountAggregateOutputType | null
  _avg: UploadHistoryAvgAggregateOutputType | null
  _sum: UploadHistorySumAggregateOutputType | null
  _min: UploadHistoryMinAggregateOutputType | null
  _max: UploadHistoryMaxAggregateOutputType | null
}

export type GetUploadHistoryGroupByPayload<T extends UploadHistoryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UploadHistoryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UploadHistoryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UploadHistoryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UploadHistoryGroupByOutputType[P]>
      }
    >
  >



export type UploadHistoryWhereInput = {
  AND?: Prisma.UploadHistoryWhereInput | Prisma.UploadHistoryWhereInput[]
  OR?: Prisma.UploadHistoryWhereInput[]
  NOT?: Prisma.UploadHistoryWhereInput | Prisma.UploadHistoryWhereInput[]
  id?: Prisma.StringFilter<"UploadHistory"> | string
  userId?: Prisma.StringFilter<"UploadHistory"> | string
  filename?: Prisma.StringFilter<"UploadHistory"> | string
  fileSize?: Prisma.IntFilter<"UploadHistory"> | number
  rowCount?: Prisma.IntFilter<"UploadHistory"> | number
  errorCount?: Prisma.IntFilter<"UploadHistory"> | number
  errors?: Prisma.JsonNullableFilter<"UploadHistory">
  status?: Prisma.StringFilter<"UploadHistory"> | string
  createdAt?: Prisma.DateTimeFilter<"UploadHistory"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type UploadHistoryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  filename?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
  rowCount?: Prisma.SortOrder
  errorCount?: Prisma.SortOrder
  errors?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type UploadHistoryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.UploadHistoryWhereInput | Prisma.UploadHistoryWhereInput[]
  OR?: Prisma.UploadHistoryWhereInput[]
  NOT?: Prisma.UploadHistoryWhereInput | Prisma.UploadHistoryWhereInput[]
  userId?: Prisma.StringFilter<"UploadHistory"> | string
  filename?: Prisma.StringFilter<"UploadHistory"> | string
  fileSize?: Prisma.IntFilter<"UploadHistory"> | number
  rowCount?: Prisma.IntFilter<"UploadHistory"> | number
  errorCount?: Prisma.IntFilter<"UploadHistory"> | number
  errors?: Prisma.JsonNullableFilter<"UploadHistory">
  status?: Prisma.StringFilter<"UploadHistory"> | string
  createdAt?: Prisma.DateTimeFilter<"UploadHistory"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type UploadHistoryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  filename?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
  rowCount?: Prisma.SortOrder
  errorCount?: Prisma.SortOrder
  errors?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.UploadHistoryCountOrderByAggregateInput
  _avg?: Prisma.UploadHistoryAvgOrderByAggregateInput
  _max?: Prisma.UploadHistoryMaxOrderByAggregateInput
  _min?: Prisma.UploadHistoryMinOrderByAggregateInput
  _sum?: Prisma.UploadHistorySumOrderByAggregateInput
}

export type UploadHistoryScalarWhereWithAggregatesInput = {
  AND?: Prisma.UploadHistoryScalarWhereWithAggregatesInput | Prisma.UploadHistoryScalarWhereWithAggregatesInput[]
  OR?: Prisma.UploadHistoryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UploadHistoryScalarWhereWithAggregatesInput | Prisma.UploadHistoryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"UploadHistory"> | string
  userId?: Prisma.StringWithAggregatesFilter<"UploadHistory"> | string
  filename?: Prisma.StringWithAggregatesFilter<"UploadHistory"> | string
  fileSize?: Prisma.IntWithAggregatesFilter<"UploadHistory"> | number
  rowCount?: Prisma.IntWithAggregatesFilter<"UploadHistory"> | number
  errorCount?: Prisma.IntWithAggregatesFilter<"UploadHistory"> | number
  errors?: Prisma.JsonNullableWithAggregatesFilter<"UploadHistory">
  status?: Prisma.StringWithAggregatesFilter<"UploadHistory"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"UploadHistory"> | Date | string
}

export type UploadHistoryCreateInput = {
  id?: string
  filename: string
  fileSize: number
  rowCount: number
  errorCount: number
  errors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status: string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutUploadHistoryInput
}

export type UploadHistoryUncheckedCreateInput = {
  id?: string
  userId: string
  filename: string
  fileSize: number
  rowCount: number
  errorCount: number
  errors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status: string
  createdAt?: Date | string
}

export type UploadHistoryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  filename?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.IntFieldUpdateOperationsInput | number
  rowCount?: Prisma.IntFieldUpdateOperationsInput | number
  errorCount?: Prisma.IntFieldUpdateOperationsInput | number
  errors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutUploadHistoryNestedInput
}

export type UploadHistoryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  filename?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.IntFieldUpdateOperationsInput | number
  rowCount?: Prisma.IntFieldUpdateOperationsInput | number
  errorCount?: Prisma.IntFieldUpdateOperationsInput | number
  errors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UploadHistoryCreateManyInput = {
  id?: string
  userId: string
  filename: string
  fileSize: number
  rowCount: number
  errorCount: number
  errors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status: string
  createdAt?: Date | string
}

export type UploadHistoryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  filename?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.IntFieldUpdateOperationsInput | number
  rowCount?: Prisma.IntFieldUpdateOperationsInput | number
  errorCount?: Prisma.IntFieldUpdateOperationsInput | number
  errors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UploadHistoryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  filename?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.IntFieldUpdateOperationsInput | number
  rowCount?: Prisma.IntFieldUpdateOperationsInput | number
  errorCount?: Prisma.IntFieldUpdateOperationsInput | number
  errors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UploadHistoryListRelationFilter = {
  every?: Prisma.UploadHistoryWhereInput
  some?: Prisma.UploadHistoryWhereInput
  none?: Prisma.UploadHistoryWhereInput
}

export type UploadHistoryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UploadHistoryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  filename?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
  rowCount?: Prisma.SortOrder
  errorCount?: Prisma.SortOrder
  errors?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UploadHistoryAvgOrderByAggregateInput = {
  fileSize?: Prisma.SortOrder
  rowCount?: Prisma.SortOrder
  errorCount?: Prisma.SortOrder
}

export type UploadHistoryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  filename?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
  rowCount?: Prisma.SortOrder
  errorCount?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UploadHistoryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  filename?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
  rowCount?: Prisma.SortOrder
  errorCount?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UploadHistorySumOrderByAggregateInput = {
  fileSize?: Prisma.SortOrder
  rowCount?: Prisma.SortOrder
  errorCount?: Prisma.SortOrder
}

export type UploadHistoryCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UploadHistoryCreateWithoutUserInput, Prisma.UploadHistoryUncheckedCreateWithoutUserInput> | Prisma.UploadHistoryCreateWithoutUserInput[] | Prisma.UploadHistoryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UploadHistoryCreateOrConnectWithoutUserInput | Prisma.UploadHistoryCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UploadHistoryCreateManyUserInputEnvelope
  connect?: Prisma.UploadHistoryWhereUniqueInput | Prisma.UploadHistoryWhereUniqueInput[]
}

export type UploadHistoryUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UploadHistoryCreateWithoutUserInput, Prisma.UploadHistoryUncheckedCreateWithoutUserInput> | Prisma.UploadHistoryCreateWithoutUserInput[] | Prisma.UploadHistoryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UploadHistoryCreateOrConnectWithoutUserInput | Prisma.UploadHistoryCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UploadHistoryCreateManyUserInputEnvelope
  connect?: Prisma.UploadHistoryWhereUniqueInput | Prisma.UploadHistoryWhereUniqueInput[]
}

export type UploadHistoryUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UploadHistoryCreateWithoutUserInput, Prisma.UploadHistoryUncheckedCreateWithoutUserInput> | Prisma.UploadHistoryCreateWithoutUserInput[] | Prisma.UploadHistoryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UploadHistoryCreateOrConnectWithoutUserInput | Prisma.UploadHistoryCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UploadHistoryUpsertWithWhereUniqueWithoutUserInput | Prisma.UploadHistoryUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UploadHistoryCreateManyUserInputEnvelope
  set?: Prisma.UploadHistoryWhereUniqueInput | Prisma.UploadHistoryWhereUniqueInput[]
  disconnect?: Prisma.UploadHistoryWhereUniqueInput | Prisma.UploadHistoryWhereUniqueInput[]
  delete?: Prisma.UploadHistoryWhereUniqueInput | Prisma.UploadHistoryWhereUniqueInput[]
  connect?: Prisma.UploadHistoryWhereUniqueInput | Prisma.UploadHistoryWhereUniqueInput[]
  update?: Prisma.UploadHistoryUpdateWithWhereUniqueWithoutUserInput | Prisma.UploadHistoryUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UploadHistoryUpdateManyWithWhereWithoutUserInput | Prisma.UploadHistoryUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UploadHistoryScalarWhereInput | Prisma.UploadHistoryScalarWhereInput[]
}

export type UploadHistoryUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UploadHistoryCreateWithoutUserInput, Prisma.UploadHistoryUncheckedCreateWithoutUserInput> | Prisma.UploadHistoryCreateWithoutUserInput[] | Prisma.UploadHistoryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UploadHistoryCreateOrConnectWithoutUserInput | Prisma.UploadHistoryCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UploadHistoryUpsertWithWhereUniqueWithoutUserInput | Prisma.UploadHistoryUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UploadHistoryCreateManyUserInputEnvelope
  set?: Prisma.UploadHistoryWhereUniqueInput | Prisma.UploadHistoryWhereUniqueInput[]
  disconnect?: Prisma.UploadHistoryWhereUniqueInput | Prisma.UploadHistoryWhereUniqueInput[]
  delete?: Prisma.UploadHistoryWhereUniqueInput | Prisma.UploadHistoryWhereUniqueInput[]
  connect?: Prisma.UploadHistoryWhereUniqueInput | Prisma.UploadHistoryWhereUniqueInput[]
  update?: Prisma.UploadHistoryUpdateWithWhereUniqueWithoutUserInput | Prisma.UploadHistoryUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UploadHistoryUpdateManyWithWhereWithoutUserInput | Prisma.UploadHistoryUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UploadHistoryScalarWhereInput | Prisma.UploadHistoryScalarWhereInput[]
}

export type UploadHistoryCreateWithoutUserInput = {
  id?: string
  filename: string
  fileSize: number
  rowCount: number
  errorCount: number
  errors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status: string
  createdAt?: Date | string
}

export type UploadHistoryUncheckedCreateWithoutUserInput = {
  id?: string
  filename: string
  fileSize: number
  rowCount: number
  errorCount: number
  errors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status: string
  createdAt?: Date | string
}

export type UploadHistoryCreateOrConnectWithoutUserInput = {
  where: Prisma.UploadHistoryWhereUniqueInput
  create: Prisma.XOR<Prisma.UploadHistoryCreateWithoutUserInput, Prisma.UploadHistoryUncheckedCreateWithoutUserInput>
}

export type UploadHistoryCreateManyUserInputEnvelope = {
  data: Prisma.UploadHistoryCreateManyUserInput | Prisma.UploadHistoryCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type UploadHistoryUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UploadHistoryWhereUniqueInput
  update: Prisma.XOR<Prisma.UploadHistoryUpdateWithoutUserInput, Prisma.UploadHistoryUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UploadHistoryCreateWithoutUserInput, Prisma.UploadHistoryUncheckedCreateWithoutUserInput>
}

export type UploadHistoryUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UploadHistoryWhereUniqueInput
  data: Prisma.XOR<Prisma.UploadHistoryUpdateWithoutUserInput, Prisma.UploadHistoryUncheckedUpdateWithoutUserInput>
}

export type UploadHistoryUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UploadHistoryScalarWhereInput
  data: Prisma.XOR<Prisma.UploadHistoryUpdateManyMutationInput, Prisma.UploadHistoryUncheckedUpdateManyWithoutUserInput>
}

export type UploadHistoryScalarWhereInput = {
  AND?: Prisma.UploadHistoryScalarWhereInput | Prisma.UploadHistoryScalarWhereInput[]
  OR?: Prisma.UploadHistoryScalarWhereInput[]
  NOT?: Prisma.UploadHistoryScalarWhereInput | Prisma.UploadHistoryScalarWhereInput[]
  id?: Prisma.StringFilter<"UploadHistory"> | string
  userId?: Prisma.StringFilter<"UploadHistory"> | string
  filename?: Prisma.StringFilter<"UploadHistory"> | string
  fileSize?: Prisma.IntFilter<"UploadHistory"> | number
  rowCount?: Prisma.IntFilter<"UploadHistory"> | number
  errorCount?: Prisma.IntFilter<"UploadHistory"> | number
  errors?: Prisma.JsonNullableFilter<"UploadHistory">
  status?: Prisma.StringFilter<"UploadHistory"> | string
  createdAt?: Prisma.DateTimeFilter<"UploadHistory"> | Date | string
}

export type UploadHistoryCreateManyUserInput = {
  id?: string
  filename: string
  fileSize: number
  rowCount: number
  errorCount: number
  errors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status: string
  createdAt?: Date | string
}

export type UploadHistoryUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  filename?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.IntFieldUpdateOperationsInput | number
  rowCount?: Prisma.IntFieldUpdateOperationsInput | number
  errorCount?: Prisma.IntFieldUpdateOperationsInput | number
  errors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UploadHistoryUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  filename?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.IntFieldUpdateOperationsInput | number
  rowCount?: Prisma.IntFieldUpdateOperationsInput | number
  errorCount?: Prisma.IntFieldUpdateOperationsInput | number
  errors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UploadHistoryUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  filename?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.IntFieldUpdateOperationsInput | number
  rowCount?: Prisma.IntFieldUpdateOperationsInput | number
  errorCount?: Prisma.IntFieldUpdateOperationsInput | number
  errors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type UploadHistorySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  filename?: boolean
  fileSize?: boolean
  rowCount?: boolean
  errorCount?: boolean
  errors?: boolean
  status?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["uploadHistory"]>

export type UploadHistorySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  filename?: boolean
  fileSize?: boolean
  rowCount?: boolean
  errorCount?: boolean
  errors?: boolean
  status?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["uploadHistory"]>

export type UploadHistorySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  filename?: boolean
  fileSize?: boolean
  rowCount?: boolean
  errorCount?: boolean
  errors?: boolean
  status?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["uploadHistory"]>

export type UploadHistorySelectScalar = {
  id?: boolean
  userId?: boolean
  filename?: boolean
  fileSize?: boolean
  rowCount?: boolean
  errorCount?: boolean
  errors?: boolean
  status?: boolean
  createdAt?: boolean
}

export type UploadHistoryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "filename" | "fileSize" | "rowCount" | "errorCount" | "errors" | "status" | "createdAt", ExtArgs["result"]["uploadHistory"]>
export type UploadHistoryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UploadHistoryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UploadHistoryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $UploadHistoryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UploadHistory"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    filename: string
    fileSize: number
    rowCount: number
    errorCount: number
    errors: runtime.JsonValue | null
    status: string
    createdAt: Date
  }, ExtArgs["result"]["uploadHistory"]>
  composites: {}
}

export type UploadHistoryGetPayload<S extends boolean | null | undefined | UploadHistoryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UploadHistoryPayload, S>

export type UploadHistoryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UploadHistoryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UploadHistoryCountAggregateInputType | true
  }

export interface UploadHistoryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UploadHistory'], meta: { name: 'UploadHistory' } }
  /**
   * Find zero or one UploadHistory that matches the filter.
   * @param {UploadHistoryFindUniqueArgs} args - Arguments to find a UploadHistory
   * @example
   * // Get one UploadHistory
   * const uploadHistory = await prisma.uploadHistory.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UploadHistoryFindUniqueArgs>(args: Prisma.SelectSubset<T, UploadHistoryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UploadHistoryClient<runtime.Types.Result.GetResult<Prisma.$UploadHistoryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UploadHistory that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UploadHistoryFindUniqueOrThrowArgs} args - Arguments to find a UploadHistory
   * @example
   * // Get one UploadHistory
   * const uploadHistory = await prisma.uploadHistory.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UploadHistoryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UploadHistoryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UploadHistoryClient<runtime.Types.Result.GetResult<Prisma.$UploadHistoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UploadHistory that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UploadHistoryFindFirstArgs} args - Arguments to find a UploadHistory
   * @example
   * // Get one UploadHistory
   * const uploadHistory = await prisma.uploadHistory.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UploadHistoryFindFirstArgs>(args?: Prisma.SelectSubset<T, UploadHistoryFindFirstArgs<ExtArgs>>): Prisma.Prisma__UploadHistoryClient<runtime.Types.Result.GetResult<Prisma.$UploadHistoryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UploadHistory that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UploadHistoryFindFirstOrThrowArgs} args - Arguments to find a UploadHistory
   * @example
   * // Get one UploadHistory
   * const uploadHistory = await prisma.uploadHistory.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UploadHistoryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UploadHistoryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UploadHistoryClient<runtime.Types.Result.GetResult<Prisma.$UploadHistoryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UploadHistories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UploadHistoryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UploadHistories
   * const uploadHistories = await prisma.uploadHistory.findMany()
   * 
   * // Get first 10 UploadHistories
   * const uploadHistories = await prisma.uploadHistory.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const uploadHistoryWithIdOnly = await prisma.uploadHistory.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UploadHistoryFindManyArgs>(args?: Prisma.SelectSubset<T, UploadHistoryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UploadHistoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UploadHistory.
   * @param {UploadHistoryCreateArgs} args - Arguments to create a UploadHistory.
   * @example
   * // Create one UploadHistory
   * const UploadHistory = await prisma.uploadHistory.create({
   *   data: {
   *     // ... data to create a UploadHistory
   *   }
   * })
   * 
   */
  create<T extends UploadHistoryCreateArgs>(args: Prisma.SelectSubset<T, UploadHistoryCreateArgs<ExtArgs>>): Prisma.Prisma__UploadHistoryClient<runtime.Types.Result.GetResult<Prisma.$UploadHistoryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UploadHistories.
   * @param {UploadHistoryCreateManyArgs} args - Arguments to create many UploadHistories.
   * @example
   * // Create many UploadHistories
   * const uploadHistory = await prisma.uploadHistory.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UploadHistoryCreateManyArgs>(args?: Prisma.SelectSubset<T, UploadHistoryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UploadHistories and returns the data saved in the database.
   * @param {UploadHistoryCreateManyAndReturnArgs} args - Arguments to create many UploadHistories.
   * @example
   * // Create many UploadHistories
   * const uploadHistory = await prisma.uploadHistory.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UploadHistories and only return the `id`
   * const uploadHistoryWithIdOnly = await prisma.uploadHistory.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UploadHistoryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UploadHistoryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UploadHistoryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UploadHistory.
   * @param {UploadHistoryDeleteArgs} args - Arguments to delete one UploadHistory.
   * @example
   * // Delete one UploadHistory
   * const UploadHistory = await prisma.uploadHistory.delete({
   *   where: {
   *     // ... filter to delete one UploadHistory
   *   }
   * })
   * 
   */
  delete<T extends UploadHistoryDeleteArgs>(args: Prisma.SelectSubset<T, UploadHistoryDeleteArgs<ExtArgs>>): Prisma.Prisma__UploadHistoryClient<runtime.Types.Result.GetResult<Prisma.$UploadHistoryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UploadHistory.
   * @param {UploadHistoryUpdateArgs} args - Arguments to update one UploadHistory.
   * @example
   * // Update one UploadHistory
   * const uploadHistory = await prisma.uploadHistory.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UploadHistoryUpdateArgs>(args: Prisma.SelectSubset<T, UploadHistoryUpdateArgs<ExtArgs>>): Prisma.Prisma__UploadHistoryClient<runtime.Types.Result.GetResult<Prisma.$UploadHistoryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UploadHistories.
   * @param {UploadHistoryDeleteManyArgs} args - Arguments to filter UploadHistories to delete.
   * @example
   * // Delete a few UploadHistories
   * const { count } = await prisma.uploadHistory.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UploadHistoryDeleteManyArgs>(args?: Prisma.SelectSubset<T, UploadHistoryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UploadHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UploadHistoryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UploadHistories
   * const uploadHistory = await prisma.uploadHistory.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UploadHistoryUpdateManyArgs>(args: Prisma.SelectSubset<T, UploadHistoryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UploadHistories and returns the data updated in the database.
   * @param {UploadHistoryUpdateManyAndReturnArgs} args - Arguments to update many UploadHistories.
   * @example
   * // Update many UploadHistories
   * const uploadHistory = await prisma.uploadHistory.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UploadHistories and only return the `id`
   * const uploadHistoryWithIdOnly = await prisma.uploadHistory.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UploadHistoryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UploadHistoryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UploadHistoryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UploadHistory.
   * @param {UploadHistoryUpsertArgs} args - Arguments to update or create a UploadHistory.
   * @example
   * // Update or create a UploadHistory
   * const uploadHistory = await prisma.uploadHistory.upsert({
   *   create: {
   *     // ... data to create a UploadHistory
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UploadHistory we want to update
   *   }
   * })
   */
  upsert<T extends UploadHistoryUpsertArgs>(args: Prisma.SelectSubset<T, UploadHistoryUpsertArgs<ExtArgs>>): Prisma.Prisma__UploadHistoryClient<runtime.Types.Result.GetResult<Prisma.$UploadHistoryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UploadHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UploadHistoryCountArgs} args - Arguments to filter UploadHistories to count.
   * @example
   * // Count the number of UploadHistories
   * const count = await prisma.uploadHistory.count({
   *   where: {
   *     // ... the filter for the UploadHistories we want to count
   *   }
   * })
  **/
  count<T extends UploadHistoryCountArgs>(
    args?: Prisma.Subset<T, UploadHistoryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UploadHistoryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UploadHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UploadHistoryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UploadHistoryAggregateArgs>(args: Prisma.Subset<T, UploadHistoryAggregateArgs>): Prisma.PrismaPromise<GetUploadHistoryAggregateType<T>>

  /**
   * Group by UploadHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UploadHistoryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UploadHistoryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UploadHistoryGroupByArgs['orderBy'] }
      : { orderBy?: UploadHistoryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UploadHistoryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUploadHistoryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UploadHistory model
 */
readonly fields: UploadHistoryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UploadHistory.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UploadHistoryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UploadHistory model
 */
export interface UploadHistoryFieldRefs {
  readonly id: Prisma.FieldRef<"UploadHistory", 'String'>
  readonly userId: Prisma.FieldRef<"UploadHistory", 'String'>
  readonly filename: Prisma.FieldRef<"UploadHistory", 'String'>
  readonly fileSize: Prisma.FieldRef<"UploadHistory", 'Int'>
  readonly rowCount: Prisma.FieldRef<"UploadHistory", 'Int'>
  readonly errorCount: Prisma.FieldRef<"UploadHistory", 'Int'>
  readonly errors: Prisma.FieldRef<"UploadHistory", 'Json'>
  readonly status: Prisma.FieldRef<"UploadHistory", 'String'>
  readonly createdAt: Prisma.FieldRef<"UploadHistory", 'DateTime'>
}
    

// Custom InputTypes
/**
 * UploadHistory findUnique
 */
export type UploadHistoryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UploadHistory
   */
  select?: Prisma.UploadHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the UploadHistory
   */
  omit?: Prisma.UploadHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UploadHistoryInclude<ExtArgs> | null
  /**
   * Filter, which UploadHistory to fetch.
   */
  where: Prisma.UploadHistoryWhereUniqueInput
}

/**
 * UploadHistory findUniqueOrThrow
 */
export type UploadHistoryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UploadHistory
   */
  select?: Prisma.UploadHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the UploadHistory
   */
  omit?: Prisma.UploadHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UploadHistoryInclude<ExtArgs> | null
  /**
   * Filter, which UploadHistory to fetch.
   */
  where: Prisma.UploadHistoryWhereUniqueInput
}

/**
 * UploadHistory findFirst
 */
export type UploadHistoryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UploadHistory
   */
  select?: Prisma.UploadHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the UploadHistory
   */
  omit?: Prisma.UploadHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UploadHistoryInclude<ExtArgs> | null
  /**
   * Filter, which UploadHistory to fetch.
   */
  where?: Prisma.UploadHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UploadHistories to fetch.
   */
  orderBy?: Prisma.UploadHistoryOrderByWithRelationInput | Prisma.UploadHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UploadHistories.
   */
  cursor?: Prisma.UploadHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UploadHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UploadHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UploadHistories.
   */
  distinct?: Prisma.UploadHistoryScalarFieldEnum | Prisma.UploadHistoryScalarFieldEnum[]
}

/**
 * UploadHistory findFirstOrThrow
 */
export type UploadHistoryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UploadHistory
   */
  select?: Prisma.UploadHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the UploadHistory
   */
  omit?: Prisma.UploadHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UploadHistoryInclude<ExtArgs> | null
  /**
   * Filter, which UploadHistory to fetch.
   */
  where?: Prisma.UploadHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UploadHistories to fetch.
   */
  orderBy?: Prisma.UploadHistoryOrderByWithRelationInput | Prisma.UploadHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UploadHistories.
   */
  cursor?: Prisma.UploadHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UploadHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UploadHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UploadHistories.
   */
  distinct?: Prisma.UploadHistoryScalarFieldEnum | Prisma.UploadHistoryScalarFieldEnum[]
}

/**
 * UploadHistory findMany
 */
export type UploadHistoryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UploadHistory
   */
  select?: Prisma.UploadHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the UploadHistory
   */
  omit?: Prisma.UploadHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UploadHistoryInclude<ExtArgs> | null
  /**
   * Filter, which UploadHistories to fetch.
   */
  where?: Prisma.UploadHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UploadHistories to fetch.
   */
  orderBy?: Prisma.UploadHistoryOrderByWithRelationInput | Prisma.UploadHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UploadHistories.
   */
  cursor?: Prisma.UploadHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UploadHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UploadHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UploadHistories.
   */
  distinct?: Prisma.UploadHistoryScalarFieldEnum | Prisma.UploadHistoryScalarFieldEnum[]
}

/**
 * UploadHistory create
 */
export type UploadHistoryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UploadHistory
   */
  select?: Prisma.UploadHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the UploadHistory
   */
  omit?: Prisma.UploadHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UploadHistoryInclude<ExtArgs> | null
  /**
   * The data needed to create a UploadHistory.
   */
  data: Prisma.XOR<Prisma.UploadHistoryCreateInput, Prisma.UploadHistoryUncheckedCreateInput>
}

/**
 * UploadHistory createMany
 */
export type UploadHistoryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UploadHistories.
   */
  data: Prisma.UploadHistoryCreateManyInput | Prisma.UploadHistoryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UploadHistory createManyAndReturn
 */
export type UploadHistoryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UploadHistory
   */
  select?: Prisma.UploadHistorySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UploadHistory
   */
  omit?: Prisma.UploadHistoryOmit<ExtArgs> | null
  /**
   * The data used to create many UploadHistories.
   */
  data: Prisma.UploadHistoryCreateManyInput | Prisma.UploadHistoryCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UploadHistoryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UploadHistory update
 */
export type UploadHistoryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UploadHistory
   */
  select?: Prisma.UploadHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the UploadHistory
   */
  omit?: Prisma.UploadHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UploadHistoryInclude<ExtArgs> | null
  /**
   * The data needed to update a UploadHistory.
   */
  data: Prisma.XOR<Prisma.UploadHistoryUpdateInput, Prisma.UploadHistoryUncheckedUpdateInput>
  /**
   * Choose, which UploadHistory to update.
   */
  where: Prisma.UploadHistoryWhereUniqueInput
}

/**
 * UploadHistory updateMany
 */
export type UploadHistoryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UploadHistories.
   */
  data: Prisma.XOR<Prisma.UploadHistoryUpdateManyMutationInput, Prisma.UploadHistoryUncheckedUpdateManyInput>
  /**
   * Filter which UploadHistories to update
   */
  where?: Prisma.UploadHistoryWhereInput
  /**
   * Limit how many UploadHistories to update.
   */
  limit?: number
}

/**
 * UploadHistory updateManyAndReturn
 */
export type UploadHistoryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UploadHistory
   */
  select?: Prisma.UploadHistorySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UploadHistory
   */
  omit?: Prisma.UploadHistoryOmit<ExtArgs> | null
  /**
   * The data used to update UploadHistories.
   */
  data: Prisma.XOR<Prisma.UploadHistoryUpdateManyMutationInput, Prisma.UploadHistoryUncheckedUpdateManyInput>
  /**
   * Filter which UploadHistories to update
   */
  where?: Prisma.UploadHistoryWhereInput
  /**
   * Limit how many UploadHistories to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UploadHistoryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UploadHistory upsert
 */
export type UploadHistoryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UploadHistory
   */
  select?: Prisma.UploadHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the UploadHistory
   */
  omit?: Prisma.UploadHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UploadHistoryInclude<ExtArgs> | null
  /**
   * The filter to search for the UploadHistory to update in case it exists.
   */
  where: Prisma.UploadHistoryWhereUniqueInput
  /**
   * In case the UploadHistory found by the `where` argument doesn't exist, create a new UploadHistory with this data.
   */
  create: Prisma.XOR<Prisma.UploadHistoryCreateInput, Prisma.UploadHistoryUncheckedCreateInput>
  /**
   * In case the UploadHistory was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UploadHistoryUpdateInput, Prisma.UploadHistoryUncheckedUpdateInput>
}

/**
 * UploadHistory delete
 */
export type UploadHistoryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UploadHistory
   */
  select?: Prisma.UploadHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the UploadHistory
   */
  omit?: Prisma.UploadHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UploadHistoryInclude<ExtArgs> | null
  /**
   * Filter which UploadHistory to delete.
   */
  where: Prisma.UploadHistoryWhereUniqueInput
}

/**
 * UploadHistory deleteMany
 */
export type UploadHistoryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UploadHistories to delete
   */
  where?: Prisma.UploadHistoryWhereInput
  /**
   * Limit how many UploadHistories to delete.
   */
  limit?: number
}

/**
 * UploadHistory without action
 */
export type UploadHistoryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UploadHistory
   */
  select?: Prisma.UploadHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the UploadHistory
   */
  omit?: Prisma.UploadHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UploadHistoryInclude<ExtArgs> | null
}
